name: Action tests

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test-foundry-any-fail:
    name: Actions Test - Foundry-fail-Any
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test Local Action
        uses: ./
        id: custom
        with:
          working-directory: ./test-contracts/hello_foundry
          fail-on: any
        continue-on-error: true

      - name: Assert that it failed
        if: steps.custom.outcome == 'failure'
        run: echo "✅ Correctly failed."

      - name: Fail if it succeeded
        if: steps.custom.outcome != 'failure'
        run: |
          echo "❌ Action unexpectedly succeeded."
          exit 1

  test-foundry-high-fail:
    name: Actions Test - Foundry-fail-High
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test Local Action
        uses: ./
        with:
          working-directory: ./test-contracts/hello_foundry
          fail-on: high
          warn-on: low

  test-foundry-any-warn:
    name: Actions Test - Foundry-warn-Any
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test Local Action
        uses: ./
        id: custom
        with:
          working-directory: ./test-contracts/hello_foundry
          warn-on: any

  test-foundry-high-warn:
    name: Actions Test - Foundry-warn-High
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test Local Action
        uses: ./
        with:
          working-directory: ./test-contracts/hello_foundry
          warn-on: high
